fontWidth=12
fontHeight=36
// Black
pixelRGB=-16777216
// Black
borderRGB=-16777216
// White
backgroundRGB=-1
xOffset=40
yOffset=40
borderWidth=2
pixelSize=4
spacerWidth=8
numCols=16
numRows=16